# Generated by Django 5.2.11 on 2026-02-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingtoken',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
