# Generated by Django 5.2.11 on 2026-05-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_webrtcsignal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebRTCSignal',
        ),
    ]
