# Generated by Django 5.2.11 on 2026-05-22 13:19

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_delete_webrtcsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='secret_key',
            field=models.CharField(default=secrets.token_hex, editable=False, max_length=64, unique=True),
        ),
    ]
