# Generated by Django 5.2.11 on 2026-05-22 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
